KirtasiyejimWebApp/Controllers/MenuController.cs
using KirtasiyejimWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KirtasiyejimWebApp.Controllers
{
    public class MenuController : Controller
    {
        KirtasiyejimDBModel db = new KirtasiyejimDBModel();
        // GET: Menu
        public ActionResult _menuView()
        {
            return PartialView(db.Categories.Where(x=> x.IsActive).ToList());
        }
    }
}

KirtasiyejimWebApp/Controllers/ShoppingCartController.cs
using KirtasiyejimWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KirtasiyejimWebApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        KirtasiyejimDBModel db = new KirtasiyejimDBModel();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            int User_ID = 0;
            if (Session["user"] != null)
            {
               User_ID = (Session["user"] as User).ID;

            }
            return View(db.ShoppingCarts.Where(x=> x.User_ID == User_ID));
        }

        public ActionResult AddProduct(string id, string quantity)
        {
            int productid = Convert.ToInt32(id);
            if (Session["user"] != null)
            {
                
                if (db.ShoppingCarts.Count(x=> x.Product_ID == productid) == 0)
                {
                    ShoppingCart sc = new ShoppingCart();
                    sc.Product_ID = productid;
                    sc.Quantity = int.Parse(quantity);
                    sc.User_ID = (Session["user"] as User).ID;
                    sc.AddedDate = DateTime.Now;
                    db.ShoppingCarts.Add(sc);
                    db.SaveChanges();
                }
                else
                {
                    int cartid = db.ShoppingCarts.FirstOrDefault(x => x.Product_ID == productid).ID;
                    ShoppingCart sc = db.ShoppingCarts.Find(cartid);
                    sc.Quantity += int.Parse(quantity);
                    db.SaveChanges();
                }
            }
            else
            {
                TempData["controller"] = "Product";
                TempData["action"] = "Detail";
                TempData["id"] = id;
                return RedirectToAction("Login", "User");
            }
            return RedirectToAction("Detail","Product", new { id= productid });
        }
    }
}

KirtasiyejimWebApp/Controllers/UserController.cs
using KirtasiyejimWebApp.Data;
using KirtasiyejimWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KirtasiyejimWebApp.Controllers
{
    public class UserController : Controller
    {
        KirtasiyejimDBModel db = new KirtasiyejimDBModel();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User u = db.Users.FirstOrDefault(x => x.Email == model.Email && x.Password == model.Password);
                    if (u!= null)
                    {
                        if (u.IsActive == true)
                        {
                            Session["user"] = u;
                            if (TempData["controller"]!= null)
                            {
                                return RedirectToAction(TempData["action"].ToString(), TempData["controller"].ToString(), new { id = Convert.ToInt32(TempData["id"]) });
                            }
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            ViewBag.hataMesaj = "Hesabınız askıya alınmıştır";
                        }
                    }
                    else
                    {
                        ViewBag.hataMesaj = "Kullanıcı bulunamadı";
                    }
                }
                catch
                {
                    ViewBag.hataMesaj = "Bir hata oluştu";
                }
            }
            return View(model);
        }
        public ActionResult LogOut()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

KirtasiyejimWebApp/Views/Shared/_LayoutPage1.cshtml
@using KirtasiyejimWebApp.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>kırtasiyejim - @ViewBag.Title * Her zaman uygun fiyatlı kırtasiye ürünleri *</title>
    <link href="~/Assets/css/MainStyle.css" rel="stylesheet" />
    <link href="~/Assets/plugins/fontawesome-6.5.1/css/all.min.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="topnavbar">
        <div class="container">
            <a href="~/Home/Index" class="brand"> <h3>Kırtasiye-<span style="color:coral">jim</span></h3></a>
            <small class="motto">Her zaman uygun fiyatlı kırtasiye ürünleri</small>
            @if (Session["user"] == null)
            {
                <div class="userandcart">
                    <a href="@Url.Action("Register","User")"><i class="fa fa-user-plus"></i> Üye Ol</a>
                    <a href="@Url.Action("Login","User")"><i class="fa fa-user"></i> Giriş Yap</a>
                    <a href="@Url.Action("Index","ShoppingCart")"><i class="fa fa-shopping-cart"></i> Sepet (0)</a>
                </div>
            }
            else
            {
                User u = Session["user"] as User;
                KirtasiyejimDBModel db = new KirtasiyejimDBModel();
                int count = db.ShoppingCarts.Count(x => x.User_ID == u.ID);

                <div class="userandcart">
                    <a href="@Url.Action("Index","ShoppingCart")"><i class="fa fa-shopping-cart"></i> Sepet (@count)</a>
                    <a href="@Url.Action("Profile","User")">@u.Name @u.Surname</a>
                    <a href="@Url.Action("LogOut","User")"> Çıkış</a>
                </div>
            }
            <div style="clear:both"></div>
        </div>
    </div>
    <div class="navbar">
        <div class="container">
            @Html.Action("_menuView", "Menu")
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>